### ISSUE TITLE
Fix git submodules

### ISSUE THREAD

**Issue by HaHeho** [AppliedAcousticsChalmers/ambisonics-for-insta360-pro#1]
The git submodules are not correctly recognized in the repository.

1) I believe https://github.com/AppliedAcousticsChalmers/ambisonics-for-insta360-pro/blob/c04068a4547296b6c6156a8af927b748f41be7fa/.gitmodules#L3
should be `        url = https://github.com/thomasdeppisch/eMagLS.git` instead.

2) The ambisonics encoding toolbox is missing, so something like the following should be added.
```
[submodule "signal_processing/ambisonic-encoding"]
	path = signal_processing/ambisonic-encoding
	url = https://github.com/AppliedAcousticsChalmers/ambisonic-encoding.git
```

In both cases, the submodules should be updated/added via the respective git commands, not by manually modifying the `.gitmodules` file directly. After a successful update, the submodules should also appear on GitHub.

**Comment by JensAhrens** [comment]
Thanks for the heads up!

This is solved by a452eae.
